const mongoose = require('mongoose');
const LeaveRegister = require('../model/LeaveRegister');
const LeaveRegisterMonthlySnapshot = require('../model/LeaveRegisterMonthlySnapshot');
const Employee = require('../../employees/model/Employee');
const Leave = require('../model/Leave');
const LeaveSettings = require('../model/LeaveSettings');
const LeavePolicySettings = require('../../settings/model/LeavePolicySettings');
const { extractISTComponents, createISTDate } = require('../../shared/utils/dateUtils');

/**
 * Leave Register Service
 * Manages complete ledger of all leave transactions with audit transparency
 */

class LeaveRegisterService {
    /**
     * Add leave transaction to register
     */
    async addTransaction(transactionData) {
        try {
            const dateCycleService = require('./dateCycleService');
            // Get period info for the transaction date
            const periodInfo = await dateCycleService.getPeriodInfo(transactionData.startDate);

            // Get previous balance for this employee and leave type
            const previousEntry = await LeaveRegister.getEmployeeBalance(
                transactionData.employeeId,
                transactionData.leaveType,
                transactionData.startDate
            );

            const openingBalance = previousEntry ? previousEntry.closingBalance : 0;

            // Create new transaction with proper period info
            const transaction = new LeaveRegister({
                ...transactionData,
                openingBalance,
                closingBalance: this.calculateClosingBalance(openingBalance, transactionData),
                // Use payroll cycle month/year instead of calendar
                month: periodInfo.payrollCycle.month,
                year: periodInfo.payrollCycle.year,
                financialYear: periodInfo.financialYear.name,
                // Store period details for reference
                payrollCycleStart: periodInfo.payrollCycle.startDate,
                payrollCycleEnd: periodInfo.payrollCycle.endDate,
                financialYearStart: periodInfo.financialYear.startDate,
                financialYearEnd: periodInfo.financialYear.endDate
            });

            const savedTransaction = await transaction.save();

            // Ripple effect: Recalculate all subsequent transactions to ensure ledger integrity
            await this.recalculateRegisterBalances(
                transactionData.employeeId,
                transactionData.leaveType,
                transactionData.startDate
            );

            return savedTransaction;
        } catch (error) {
            if (error.name === 'ValidationError') {
                console.error('[LeaveRegister] ValidationError fields:', Object.keys(error.errors || {}).join(', '));
            }
            console.error('Error adding leave transaction:', error.message);
            throw error;
        }
    }

    /**
     * Add earned leave credit (auto-generated)
     */
    async addEarnedLeaveCredit(employeeId, elEarned, month, year, calculationBreakdown = null, cycleEnd = null) {
        try {
            const employee = await Employee.findById(employeeId);
            if (!employee) throw new Error('Employee not found');

            // Use provided cycleEnd date, else fallback to 15th of month to locate the correct payroll cycle.
            const cycleDate = cycleEnd || new Date(year, month - 1, 15);

            const transactionData = {
                employeeId,
                empNo: employee.emp_no,
                employeeName: employee.employee_name || 'N/A',
                designation: employee.designation || 'N/A',
                department: employee.department || 'N/A',
                divisionId: employee.division_id,
                departmentId: employee.department_id,
                dateOfJoining: employee.doj,
                employmentStatus: employee.is_active ? 'active' : 'inactive',

                leaveType: 'EL',
                transactionType: 'CREDIT',
                startDate: cycleDate, // addTransaction handles cycle categorization based on this
                endDate: cycleDate,
                days: elEarned,
                reason: 'Earned Leave - Auto Credit',
                status: 'APPROVED',

                autoGenerated: true,
                autoGeneratedType: 'EARNED_LEAVE',
                calculationBreakdown
            };

            return await this.addTransaction(transactionData);
        } catch (error) {
            console.error('Error adding earned leave credit:', error);
            throw error;
        }
    }

    /**
     * Add leave debit (when leave is availed)
     * Supports smart priority-based substitution (CL > CCL > EL) for CL applications.
     * @param {Object} leaveRecord - The approved leave document
     * @param {mongoose.Types.ObjectId} [approvedByUserId] - User ID of the approver
     */
    async addLeaveDebit(leaveRecord, approvedByUserId = null) {
        try {
            const employee = await Employee.findById(leaveRecord.employeeId)
                .populate('department_id', 'name')
                .populate('designation_id', 'name');
            if (!employee) throw new Error('Employee not found');

            const employeeName = employee.employee_name || 'N/A';
            const designation = (employee.designation_id && employee.designation_id.name) || employee.designation?.name || 'N/A';
            const department = (employee.department_id && employee.department_id.name) || employee.department?.name || 'N/A';

            const originalLeaveType = leaveRecord.leaveType === 'LOP' ? 'LOP' : (leaveRecord.leaveType || 'CL');
            const statusUpper = String(leaveRecord.status || 'approved').toUpperCase();
            const status = ['PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'].includes(statusUpper) ? statusUpper : 'APPROVED';
            const approvedBy = approvedByUserId && mongoose.Types.ObjectId.isValid(approvedByUserId) ? approvedByUserId : undefined;

            // --- SMART DEDUCTION LOGIC FOR CL ---
            let clEntry = undefined;
            let useCCL = false;
            let useEL = false;

            if (originalLeaveType === 'CL') {
                const policy = await LeavePolicySettings.getSettings();
                const settings = await LeaveSettings.getActiveSettings('leave');
                const limitConfig = policy.monthlyLimitSettings;

                // Priority Substitution only if CCL/EL are included in limit AND hidden from types list
                const isCCLHidden = !settings?.types?.some(t => t.code === 'CCL' && t.isActive);
                const isELHidden = !settings?.types?.some(t => t.code === 'EL' && t.isActive);
                
                useCCL = limitConfig.includeCCL && isCCLHidden;
                useEL = limitConfig.includeEL && isELHidden;

                const dateCycleService = require('./dateCycleService');
                const periodInfo = await dateCycleService.getPeriodInfo(leaveRecord.fromDate);
                
                // Fetch current limits/balances snapshot for ALL relevant types (no leaveType filter)
                const registerResult = await this.getLeaveRegister(
                    { employeeId: leaveRecord.employeeId, balanceAsOf: true },
                    periodInfo.payrollCycle.month,
                    periodInfo.payrollCycle.year
                );
                const registerList = (Array.isArray(registerResult) ? registerResult : (registerResult?.data || []));
                const empEntry = registerList[0]; // We filtered by employeeId
                clEntry = empEntry?.monthlySubLedgers?.find(s => s.month === periodInfo.payrollCycle.month && s.year === periodInfo.payrollCycle.year);

                if (useCCL || useEL) {
                    // Priority 1: Use CL up to its monthly cap
                    const clCap = clEntry?.casualLeave?.allowedRemaining ?? 0;
                    const totalDaysRequested = leaveRecord.numberOfDays;
                    
                    let remainingToDeduct = totalDaysRequested;
                    const deductions = [];

                    // 1. CL (Priority 1)
                    if (remainingToDeduct > 0) {
                        const clSpend = Math.min(remainingToDeduct, clCap);
                        if (clSpend > 0) {
                            deductions.push({ type: 'CL', days: clSpend, reason: leaveRecord.purpose });
                            remainingToDeduct -= clSpend;
                        }
                    }

                    // 2. CCL (Priority 2)
                    if (remainingToDeduct > 0 && useCCL) {
                        const cclBalance = await this.getCurrentBalance(leaveRecord.employeeId, 'CCL', leaveRecord.fromDate);
                        const cclSpend = Math.min(remainingToDeduct, cclBalance);
                        if (cclSpend > 0) {
                            deductions.push({ type: 'CCL', days: cclSpend, reason: `Substituted for CL Application: ${leaveRecord.purpose}` });
                            remainingToDeduct -= cclSpend;
                        }
                    }

                    // 3. EL (Priority 3)
                    if (remainingToDeduct > 0 && useEL) {
                        const elBalance = await this.getCurrentBalance(leaveRecord.employeeId, 'EL', leaveRecord.fromDate);
                        const elSpend = Math.min(remainingToDeduct, elBalance);
                        if (elSpend > 0) {
                            deductions.push({ type: 'EL', days: elSpend, reason: `Substituted for CL Application: ${leaveRecord.purpose}` });
                            remainingToDeduct -= elSpend;
                        }
                    }

                    // 4. Any leftover (Force back to CL if total limit allowed but specific hidden credits exhausted)
                    if (remainingToDeduct > 0) {
                        // Find if we already have a CL entry to merge, or add new
                        const clIdx = deductions.findIndex(d => d.type === 'CL');
                        if (clIdx > -1) deductions[clIdx].days += remainingToDeduct;
                        else deductions.push({ type: 'CL', days: remainingToDeduct, reason: leaveRecord.purpose });
                    }

                    // Execute Transactions
                    let lastResult = null;
                    for (const d of deductions) {
                        lastResult = await this.addTransaction({
                            employeeId: leaveRecord.employeeId,
                            empNo: employee.emp_no,
                            employeeName, designation, department,
                            divisionId: employee.division_id,
                            departmentId: employee.department_id,
                            dateOfJoining: employee.doj,
                            employmentStatus: employee.is_active ? 'active' : 'inactive',
                            leaveType: d.type,
                            transactionType: 'DEBIT',
                            startDate: leaveRecord.fromDate,
                            endDate: leaveRecord.toDate,
                            days: d.days,
                            applicationId: leaveRecord._id,
                            applicationDate: leaveRecord.createdAt,
                            approvalDate: leaveRecord.updatedAt,
                            approvedBy, status,
                            reason: d.reason,
                            // Snapshot limits
                            monthlyCLLimit: clEntry?.casualLeave?.monthlyCLLimit ?? 0,
                            monthlyCCLLimit: useCCL ? (clEntry?.compensatoryOff?.cclBalance ?? 0) : 0,
                            monthlyELLimit: useEL ? (clEntry?.earnedLeave?.elBalance ?? 0) : 0,
                            monthlyCombinedLimit: clEntry?.monthlyAllowedLimit ?? 0,
                            pendingLeavesBeforeAction: clEntry?.pendingAllDays ?? 0
                        });
                    }
                    return lastResult;
                }
            }

            // Fallback: Standard single-type debit
            const transactionData = {
                employeeId: leaveRecord.employeeId,
                empNo: employee.emp_no,
                employeeName, designation, department,
                divisionId: employee.division_id,
                departmentId: employee.department_id,
                dateOfJoining: employee.doj,
                employmentStatus: employee.is_active ? 'active' : 'inactive',
                leaveType: originalLeaveType,
                transactionType: 'DEBIT',
                startDate: leaveRecord.fromDate,
                endDate: leaveRecord.toDate,
                days: leaveRecord.numberOfDays,
                applicationId: leaveRecord._id,
                applicationDate: leaveRecord.createdAt,
                approvalDate: leaveRecord.updatedAt,
                approvedBy, status,
                reason: leaveRecord.purpose,
                // Snapshot limits if available
                monthlyCLLimit: typeof clEntry !== 'undefined' ? (clEntry?.casualLeave?.monthlyCLLimit ?? 0) : 0,
                monthlyCCLLimit: typeof clEntry !== 'undefined' ? (clEntry?.compensatoryOff?.cclBalance ?? 0) : 0,
                monthlyELLimit: typeof clEntry !== 'undefined' ? (clEntry?.earnedLeave?.elBalance ?? 0) : 0,
                monthlyCombinedLimit: typeof clEntry !== 'undefined' ? (clEntry?.monthlyAllowedLimit ?? 0) : 0,
                pendingLeavesBeforeAction: typeof clEntry !== 'undefined' ? (clEntry?.pendingAllDays ?? 0) : 0
            };

            return await this.addTransaction(transactionData);
        } catch (error) {
            console.error('Error adding leave debit:', error);
            throw error;
        }
    }

    /**
     * Reverse leave debit (when leave is cancelled/rejected)
     */
    async reverseLeaveDebit(leaveRecord, cancelledByUserId = null) {
        try {
            const employee = await Employee.findById(leaveRecord.employeeId)
                .populate('department_id', 'name')
                .populate('designation_id', 'name');
            if (!employee) throw new Error('Employee not found');

            const employeeName = employee.employee_name || 'N/A';
            const designation = (employee.designation_id && employee.designation_id.name) || employee.designation?.name || 'N/A';
            const department = (employee.department_id && employee.department_id.name) || employee.department?.name || 'N/A';

            const leaveType = leaveRecord.leaveType === 'LOP' ? 'LOP' : (leaveRecord.leaveType || 'CL');
            const statusUpper = String(leaveRecord.status || 'cancelled').toUpperCase();
            
            const transactionData = {
                employeeId: leaveRecord.employeeId,
                empNo: employee.emp_no,
                employeeName,
                designation,
                department,
                divisionId: employee.division_id,
                departmentId: employee.department_id,
                dateOfJoining: employee.doj,
                employmentStatus: employee.is_active ? 'active' : 'inactive',

                leaveType,
                transactionType: 'CREDIT', // Reversing a debit is a credit
                startDate: leaveRecord.fromDate,
                endDate: leaveRecord.toDate,
                days: leaveRecord.numberOfDays,
                applicationId: leaveRecord._id,
                applicationDate: leaveRecord.createdAt,
                approvalDate: new Date(),
                approvedBy: cancelledByUserId,
                status: statusUpper,
                reason: 'Leave Application Cancelled/Reversed'
            };

            return await this.addTransaction(transactionData);
        } catch (error) {
            console.error('Error reversing leave debit:', error);
            throw error;
        }
    }

    /**
     * Recalculate all balances for an employee's leave type from a specific start date.
     * Ensures the ledger chain is consistent (Opening of N+1 = Closing of N).
     * @param {string} employeeId - Employee ID
     * @param {string} leaveType - Leave type (CL, EL, CCL, etc.)
     * @param {Date} fromDate - Date to start recalculation from
     */
    async recalculateRegisterBalances(employeeId, leaveType, fromDate) {
        try {
            // 1. Get the very last transaction BEFORE the start date to get the true starting point
            const previousEntry = await LeaveRegister.findOne({
                employeeId,
                leaveType,
                startDate: { $lt: fromDate }
            }).sort({ startDate: -1, createdAt: -1 });

            let currentBalance = previousEntry ? previousEntry.closingBalance : 0;

            // 2. Get all transactions from the start date onwards, sorted chronologically
            // We use { $gte: fromDate } to include the one we just added or modified
            const transactions = await LeaveRegister.find({
                employeeId,
                leaveType,
                startDate: { $gte: fromDate }
            }).sort({ startDate: 1, createdAt: 1 });

            // 3. Update each transaction in the chain
            for (const tx of transactions) {
                tx.openingBalance = currentBalance;
                tx.closingBalance = this.calculateClosingBalance(currentBalance, tx);
                // Use markModified if needed, but Mongoose usually detects changes to these fields
                await tx.save();
                currentBalance = tx.closingBalance;
            }

            // 4. Sync the FINAL closing balance to the Employee model
            await this.updateEmployeeBalance(employeeId, leaveType);
            
            return true;
        } catch (error) {
            console.error('Error recalculating register balances:', error);
            throw error;
        }
    }

    /**
     * Add earned leave credit (auto-generated)
     */
    async addEarnedLeaveCredit(employeeId, elEarned, month, year, calculationBreakdown = null) {
        try {
            const employee = await Employee.findById(employeeId);
            if (!employee) {
                throw new Error('Employee not found');
            }

            // Get payroll cycle info for the given month/year
            const cycleDate = new Date(year, month - 1, 15); // Middle of month to get correct cycle
            const periodInfo = await dateCycleService.getPeriodInfo(cycleDate);

            const transactionData = {
                employeeId,
                empNo: employee.emp_no,
                employeeName: employee.name,
                designation: employee.designation || 'N/A',
                department: employee.department || 'N/A',
                divisionId: employee.division_id,
                departmentId: employee.department_id,
                dateOfJoining: employee.date_of_joining,
                employmentStatus: employee.is_active ? 'active' : 'inactive',

                leaveType: 'EL',
                transactionType: 'CREDIT',
                startDate: periodInfo.payrollCycle.startDate,
                endDate: periodInfo.payrollCycle.startDate,
                days: elEarned,
                reason: 'Earned Leave - Auto Credit',
                status: 'APPROVED',

                // Use payroll cycle period info
                month: periodInfo.payrollCycle.month,
                year: periodInfo.payrollCycle.year,
                financialYear: periodInfo.financialYear.name,
                autoGenerated: true,
                autoGeneratedType: 'EARNED_LEAVE',
                calculationBreakdown,

                // Store period details
                payrollCycleStart: periodInfo.payrollCycle.startDate,
                payrollCycleEnd: periodInfo.payrollCycle.endDate,
                financialYearStart: periodInfo.financialYear.startDate,
                financialYearEnd: periodInfo.financialYear.endDate
            };

            return await this.addTransaction(transactionData);
        } catch (error) {
            console.error('Error adding earned leave credit:', error);
            throw error;
        }
    }


    /**
     * Add an ADJUSTMENT transaction for an employee's leave balance.
     * Used by admin/HR to correct CL/other leave balances via the register adjust API.
     */
    async addAdjustment(employeeId, leaveType, days, reason) {
        try {
            const employee = await Employee.findById(employeeId)
                .select('_id emp_no employee_name designation_id department_id division_id doj is_active')
                .populate('designation_id', 'name')
                .populate('department_id', 'name')
                .populate('division_id', 'name');
            if (!employee) {
                throw new Error('Employee not found');
            }

            const employeeName = employee.employee_name || 'N/A';
            const designation = (employee.designation_id && employee.designation_id.name) || employee.designation?.name || 'N/A';
            const department = (employee.department_id && employee.department_id.name) || employee.department?.name || 'N/A';

            const now = new Date();
            const transactionData = {
                employeeId: employee._id,
                empNo: employee.emp_no,
                employeeName,
                designation,
                department,
                divisionId: employee.division_id,
                departmentId: employee.department_id,
                dateOfJoining: employee.doj,
                employmentStatus: employee.is_active ? 'active' : 'inactive',

                leaveType,
                transactionType: 'ADJUSTMENT',
                startDate: now,
                endDate: now,
                days,
                reason,
                status: 'APPROVED',
                autoGenerated: false
            };

            return await this.addTransaction(transactionData);
        } catch (error) {
            console.error('Error adding adjustment transaction:', error);
            throw error;
        }
    }

    /**
     * Record EL used in payroll (when batch is completed).
     * Debits employee's EL balance and marks transaction as included in payroll.
     * @param {string} employeeId - Employee ID
     * @param {number} days - EL days used in payroll
     * @param {string} month - Payroll month YYYY-MM
     * @param {ObjectId} [payrollBatchId] - Optional batch reference
     */
    async addELUsedInPayroll(employeeId, days, month, payrollBatchId = null) {
        if (!employeeId || days == null || days <= 0) return null;
        const employee = await Employee.findById(employeeId)
            .select('_id emp_no employee_name designation_id department_id division_id doj is_active')
            .populate('designation_id', 'name')
            .populate('department_id', 'name')
            .populate('division_id', 'name')
            .lean();
        if (!employee) {
            throw new Error('Employee not found');
        }
        const [y, m] = month.split('-').map(Number);
        const cycleDate = new Date(y, m - 1, 15);
        const periodInfo = await dateCycleService.getPeriodInfo(cycleDate);
        const designation = (employee.designation_id && employee.designation_id.name) || 'N/A';
        const department = (employee.department_id && employee.department_id.name) || 'N/A';
        const transactionData = {
            employeeId: employee._id,
            empNo: employee.emp_no,
            employeeName: employee.employee_name || 'N/A',
            designation,
            department,
            divisionId: employee.division_id,
            departmentId: employee.department_id,
            dateOfJoining: employee.doj,
            employmentStatus: employee.is_active ? 'active' : 'inactive',
            leaveType: 'EL',
            transactionType: 'DEBIT',
            startDate: periodInfo.payrollCycle.startDate,
            endDate: periodInfo.payrollCycle.endDate,
            days: Number(days),
            reason: 'Included in payroll',
            status: 'APPROVED',
            autoGenerated: true,
            autoGeneratedType: 'PAYROLL_USE',
            includedInPayroll: true,
            payrollBatchId: payrollBatchId || undefined
        };
        return await this.addTransaction(transactionData);
    }

    /**
     * Get leave register with filters
     */
    async getLeaveRegister(filters = {}, month = null, year = null) {
        try {
            const dateCycleService = require('./dateCycleService');
            const today = new Date();
            const baseYearNum = (year != null && year !== '') ? Number(year) : today.getFullYear();
            const baseMonthNum = (month != null && month !== '') ? Number(month) : (today.getMonth() + 1);
            const midOfMonth = new Date(baseYearNum, baseMonthNum - 1, 15);
            const periodInfo = await dateCycleService.getPeriodInfo(midOfMonth);

            // Determine the financial year
            let fyName = filters.financialYear || periodInfo.financialYear.name;
            filters.financialYear = fyName;
            const fyStart = periodInfo.financialYear.startDate;

            const registerData = await LeaveRegister.getLeaveRegister(filters, null, null); // Pass null, null to use financialYear
            console.log(`[DEBUG] getLeaveRegister: Filtered by FY=${fyName}, Found ${registerData.length} records`);


            // Batch-fetch all employees so we always have designation/department/division (model populate only has name, email)
            const rawData = Array.isArray(registerData) ? registerData : [];
            const employeeIds = [...new Set(
                rawData
                    .map((t) => t.employeeId && (t.employeeId._id || t.employeeId))
                    .filter(Boolean)
            )];
            const employeesList = employeeIds.length > 0
                ? await Employee.find({ _id: { $in: employeeIds } })
                    .select('_id emp_no employee_name designation_id department_id division_id doj is_active')
                    .populate('designation_id', 'name')
                    .populate('department_id', 'name')
                    .populate('division_id', 'name')
                    .lean()
                : [];
            const empMap = new Map(employeesList.map((e) => [e._id.toString(), e]));

            const populatedData = rawData.map((transaction) => {
                const empId = transaction.employeeId && (transaction.employeeId._id || transaction.employeeId);
                if (!empId) return transaction;
                const emp = empMap.get(empId.toString());
                if (!emp) return transaction;
                const designation = (emp.designation_id && emp.designation_id.name) || 'N/A';
                const department = (emp.department_id && emp.department_id.name) || 'N/A';
                const divisionName = (emp.division_id && emp.division_id.name) || 'N/A';
                transaction.employeeName = emp.employee_name || 'N/A';
                transaction.designation = designation;
                transaction.department = department;
                transaction.divisionName = divisionName;
                transaction.dateOfJoining = emp.doj;
                transaction.employmentStatus = emp.is_active ? 'active' : 'inactive';
                transaction.employeeId = {
                    _id: emp._id,
                    id: emp._id,
                    empNo: emp.emp_no,
                    name: emp.employee_name,
                    designation,
                    department,
                    division: divisionName,
                    doj: emp.doj,
                    status: emp.is_active ? 'active' : 'inactive'
                };
                return transaction;
            });

            // Group by employee and provide yearly ledger with monthly sub-ledgers
            // For UI month labels we must follow payroll-cycle month/year, not just calendar month.
            let monthsInOrderOverride = null;
            try {
                const dateCycleService = require('./dateCycleService');
                if (fyStart) {
                    const base = new Date(fyStart);
                    base.setDate(15);
                    monthsInOrderOverride = [];
                    for (let i = 0; i < 12; i++) {
                        const repDate = new Date(base);
                        repDate.setMonth(base.getMonth() + i);
                        repDate.setDate(15);
                        const periodInfo = await dateCycleService.getPeriodInfo(repDate);
                        const m = periodInfo.payrollCycle.month;
                        const y = periodInfo.payrollCycle.year;
                        monthsInOrderOverride.push({ month: m, year: y, key: `${y}-${m}` });
                    }
                }
            } catch (e) {
                // Fallback to old behavior if period resolution fails.
                monthsInOrderOverride = null;
            }

            let groupedData = this.groupByEmployeeYearly(populatedData, fyStart, monthsInOrderOverride);



            // When viewing register for a month (not a single employee), ensure ALL active employees in scope are listed.
            if (!filters.employeeId && !filters.empNo && month && year) {
                const existingIds = new Set(groupedData.map((entry) => entry.employee?.id?.toString() || entry.employee?._id?.toString()).filter(Boolean));
                const empQuery = { is_active: true };
                if (filters.divisionId) empQuery.division_id = filters.divisionId;
                if (filters.departmentId) empQuery.department_id = filters.departmentId;
                
                const extraEmployees = await Employee.find(empQuery)
                    .select('_id emp_no employee_name designation_id department_id division_id doj is_active casualLeaves paidLeaves compensatoryOffs')
                    .populate('designation_id', 'name')
                    .populate('department_id', 'name')
                    .populate('division_id', 'name')
                    .lean();

                for (const emp of extraEmployees) {
                    const idStr = emp._id.toString();
                    if (existingIds.has(idStr)) continue;
                    
                    const clBalance = typeof emp.casualLeaves === 'number' ? emp.casualLeaves : 0;
                    const elBalance = typeof emp.paidLeaves === 'number' ? emp.paidLeaves : 0;
                    const cclBalance = typeof emp.compensatoryOffs === 'number' ? emp.compensatoryOffs : 0;
                    
                    groupedData.push({
                        employee: {
                            id: emp._id,
                            empNo: emp.emp_no,
                            name: emp.employee_name,
                            designation: emp.designation_id?.name || 'N/A',
                            department: emp.department_id?.name || 'N/A',
                            division: emp.division_id?.name || 'N/A',
                            doj: emp.doj,
                            status: emp.is_active ? 'active' : 'inactive'
                        },
                        monthlySubLedgers: [{
                            month: Number(month),
                            year: Number(year),
                            casualLeave: { openingBalance: 0, accruedThisMonth: 0, earnedCCL: 0, usedThisMonth: 0, expired: 0, balance: clBalance, carryForward: 0 },
                            earnedLeave: { openingBalance: 0, accruedThisMonth: 0, usedThisMonth: 0, balance: elBalance },
                            compensatoryOff: { openingBalance: 0, earned: 0, used: 0, expired: 0, balance: cclBalance },
                            totalPaidBalance: clBalance + elBalance + cclBalance,
                            transactions: []
                        }]
                    });
                }
            }

            // When balance-as-of was requested for one employee and register has no transactions, fallback to Employee.casualLeaves
            if (filters.balanceAsOf && (filters.employeeId || filters.empNo) && groupedData.length === 0) {
                const emp = filters.employeeId
                    ? await Employee.findById(filters.employeeId)
                        .select('_id emp_no employee_name designation_id department_id division_id doj is_active casualLeaves paidLeaves compensatoryOffs')
                        .populate('designation_id', 'name')
                        .populate('department_id', 'name')
                        .populate('division_id', 'name')
                        .lean()
                    : await Employee.findOne({ emp_no: filters.empNo })
                        .select('_id emp_no employee_name designation_id department_id division_id doj is_active casualLeaves paidLeaves compensatoryOffs')
                        .populate('designation_id', 'name')
                        .populate('department_id', 'name')
                        .populate('division_id', 'name')
                        .lean();
                if (emp) {
                    const clBalance = typeof emp.casualLeaves === 'number' ? emp.casualLeaves : 0;
                    const elBalance = typeof emp.paidLeaves === 'number' ? emp.paidLeaves : 0;
                    const cclBalance = typeof emp.compensatoryOffs === 'number' ? emp.compensatoryOffs : 0;
                    groupedData = [{
                        employee: {
                            id: emp._id,
                            empNo: emp.emp_no,
                            name: emp.employee_name,
                            designation: emp.designation_id?.name || 'N/A',
                            department: emp.department_id?.name || 'N/A',
                            division: emp.division_id?.name || 'N/A',
                            doj: emp.doj,
                            status: emp.is_active ? 'active' : 'inactive'
                        },
                        monthlySubLedgers: [{
                            month: Number(month),
                            year: Number(year),
                            casualLeave: { openingBalance: 0, accruedThisMonth: 0, earnedCCL: 0, usedThisMonth: 0, expired: 0, balance: clBalance, carryForward: 0 },
                            earnedLeave: { openingBalance: 0, accruedThisMonth: 0, usedThisMonth: 0, balance: elBalance },
                            compensatoryOff: { openingBalance: 0, earned: 0, used: 0, expired: 0, balance: cclBalance },
                            totalPaidBalance: clBalance + elBalance + cclBalance,
                            transactions: []
                        }]
                    }];
                }
            }

            // 3. Apply Policy-Driven Monthly Limits
            const LeaveSettings = require('../model/LeaveSettings');
            const LeavePolicySettings = require('../../settings/model/LeavePolicySettings');
            const policySettings = await LeavePolicySettings.getSettings();
            
            const limitConfig = policySettings?.monthlyLimitSettings || { 
                mode: 'accumulative', 
                defaultMonthlyCap: 1, 
                maxUsableLimit: 4, 
                protectFutureMonths: true,
                includeCCL: true, 
                includeEL: true, 
                logicType: 'ADDITIVE' 
            };

            const mode = limitConfig.mode || 'accumulative';
            const defaultMonthlyCap = limitConfig.defaultMonthlyCap ?? 1;
            const maxUsableLimit = limitConfig.maxUsableLimit ?? 4;
            const protectFutureMonths = limitConfig.protectFutureMonths !== false;
            
            // Generate list of months in FY up to target month
            const monthsToProcess = [];
            const fyIst = extractISTComponents(fyStart);
            const targetIst = extractISTComponents(midOfMonth);
            let cursor = createISTDate(`${fyIst.year}-${String(fyIst.month).padStart(2, '0')}-15`);
            while (true) {
                const cIst = extractISTComponents(cursor);
                monthsToProcess.push({ month: cIst.month, year: cIst.year });
                if (cIst.year > targetIst.year || (cIst.year === targetIst.year && cIst.month >= targetIst.month)) {
                    break;
                }
                const nextMonth = cIst.month === 12 ? 1 : cIst.month + 1;
                const nextYear = cIst.month === 12 ? cIst.year + 1 : cIst.year;
                cursor = createISTDate(`${nextYear}-${String(nextMonth).padStart(2, '0')}-15`);
            }

            // Precompute payroll-cycle windows for each month we might use in carry-forward.
            // We bucket pending leaves by where their `fromDate` falls, matching how ledger debits
            // are attributed (ledger uses leave.startDate derived from fromDate -> periodInfo).
            const pendingStatuses = ['pending', 'hod_approved', 'manager_approved', 'hr_approved'];
            const monthPayrollWindows = [];
            {
                for (const mInfo of monthsToProcess) {
                    const mid = new Date(mInfo.year, mInfo.month - 1, 15);
                    const pInfo = await dateCycleService.getPeriodInfo(mid);
                    monthPayrollWindows.push({
                        month: mInfo.month,
                        year: mInfo.year,
                        key: `${mInfo.year}-${mInfo.month}`,
                        start: pInfo.payrollCycle.startDate,
                        end: pInfo.payrollCycle.endDate
                    });
                }
            }
            const windowStartMs = monthPayrollWindows.length > 0 ? monthPayrollWindows[0].start.getTime() : null;
            const windowEndMs = monthPayrollWindows.length > 0 ? monthPayrollWindows[monthPayrollWindows.length - 1].end.getTime() : null;


            for (const entry of groupedData) {
                const empId = entry.employee?.id || entry.employee?._id;
                const emp = employeesList.find(e => e._id.toString() === empId.toString());
                if (!empId) continue;

                // Determine Monthly Cap (Department Override vs Default)
                let monthlyCap = defaultMonthlyCap;
                if (emp?.department_id?.leaveLimits?.monthlyLimit > 0) {
                    monthlyCap = emp.department_id.leaveLimits.monthlyLimit;
                }

                // Calculate Experience-Based Allotment for Safety Rule
                let annualCL = policySettings.annualCLReset?.resetToBalance || 12;
                if (emp?.doj && policySettings.annualCLReset?.casualLeaveByExperience?.length > 0) {
                    const doj = new Date(emp.doj);
                    const diffMs = today - doj;
                    const years = diffMs / (1000 * 60 * 60 * 24 * 365.25);
                    const matchingTier = [...policySettings.annualCLReset.casualLeaveByExperience]
                        .sort((a, b) => a.minYears - b.minYears)
                        .find(t => years >= t.minYears && years <= t.maxYears);
                    if (matchingTier) annualCL = matchingTier.casualLeave;
                }

                // Process months to determine carry-forward limit
                let limitCarrier = 0;
                let finalMonthAllowed = 0;

                // Pending lock buckets per month (used + pending should reduce carried quota).
                const pendingByMonthKey = {};
                for (const w of monthPayrollWindows) {
                    pendingByMonthKey[w.key] = { pendingCLDays: 0, pendingAllDays: 0 };
                }

                // Fetch pending leaves once for the whole window, then bucket by monthPayrollWindows.
                // This avoids querying per month.
                if (windowStartMs != null && windowEndMs != null) {
                    const pendingLeaves = await Leave.find({
                        employeeId: empId,
                        fromDate: { $gte: new Date(windowStartMs), $lte: new Date(windowEndMs) },
                        status: { $in: pendingStatuses },
                        isActive: true
                    }).select('leaveType numberOfDays fromDate').lean();

                    for (const l of pendingLeaves) {
                        const leaveFromMs = new Date(l.fromDate).getTime();
                        let bucketed = false;
                        for (const w of monthPayrollWindows) {
                            const startMs = w.start.getTime();
                            const endMs = w.end.getTime();
                            if (leaveFromMs >= startMs && leaveFromMs <= endMs) {
                                const isCL = l.leaveType === 'CL';
                                pendingByMonthKey[w.key].pendingAllDays += (l.numberOfDays || 0);
                                if (isCL) pendingByMonthKey[w.key].pendingCLDays += (l.numberOfDays || 0);
                                bucketed = true;
                                break;
                            }
                        }
                        // If a leaveFromMs doesn't fall in any window (edge case), ignore it for locking.
                        if (!bucketed) continue;
                    }

                    // (Optional for UI drill-down): write pending into all month sub-ledgers we return.
                    for (const sub of entry.monthlySubLedgers) {
                        const key = `${sub.year}-${sub.month}`;
                        if (!pendingByMonthKey[key]) continue;
                        sub.casualLeave.pendingThisMonth = pendingByMonthKey[key].pendingCLDays;
                        sub.pendingAllDays = pendingByMonthKey[key].pendingAllDays;
                    }
                }

                for (let i = 0; i < monthsToProcess.length; i++) {
                    const mInfo = monthsToProcess[i];
                    const sub = entry.monthlySubLedgers.find(s => s.month === mInfo.month && s.year === mInfo.year);
                    
                    if (mode === 'unrestricted') {
                        finalMonthAllowed = 999; // Essentially infinity, will be capped by balance later
                        continue;
                    }

                    // Calculate Limit for this month
                    let monthLimit = monthlyCap + limitCarrier;
                    monthLimit = Math.min(monthLimit, maxUsableLimit);

                    // Safety Rule: Protect Future Months
                    if (protectFutureMonths) {
                        const totalMonthsInFY = 12;
                        const monthsRemainingAfterThis = totalMonthsInFY - (i + 1);
                        // We need to ensure we leave at least 1 CL for each remaining month
                        const clBalance = sub?.casualLeave?.balance || (i > 0 ? entry.monthlySubLedgers[i-1].casualLeave.balance : (emp?.casualLeaves || 0));
                        const safeLimit = Math.max(0, clBalance - (monthsRemainingAfterThis * 1));
                        monthLimit = Math.min(monthLimit, safeLimit);
                    }

                    // How much was used?
                    const used = sub?.casualLeave?.usedThisMonth || 0;
                    const pendingCLDays = pendingByMonthKey[`${mInfo.year}-${mInfo.month}`]?.pendingCLDays || 0;
                    const lockedCLDays = used + pendingCLDays;
                    
                    if (mInfo.month === baseMonthNum && mInfo.year === baseYearNum) {
                        finalMonthAllowed = monthLimit;
                    }

                    // Update carrier for next month
                    if (mode === 'accumulative') {
                        // Carry forward only the un-locked (un-used AND not pending) quota.
                        limitCarrier = Math.max(0, monthLimit - lockedCLDays);
                    } else {
                        // strict/unrestricted: do not carry locked quota forward as per policy mode
                        limitCarrier = 0;
                    }
                }

                // Inject limits into the requested month's sub-ledger
                const targetSub = entry.monthlySubLedgers.find(s => s.month === baseMonthNum && s.year === baseYearNum);
                if (targetSub) {
                    const clBalance = targetSub.casualLeave.balance || 0;
                    const cclBalance = targetSub.compensatoryOff.balance || 0;
                    const elBalance = targetSub.earnedLeave.balance || 0;
                    const targetKey = `${baseYearNum}-${baseMonthNum}`;
                    const pendingCLDays = pendingByMonthKey[targetKey]?.pendingCLDays || 0;
                    const pendingAllDays = pendingByMonthKey[targetKey]?.pendingAllDays || 0;

                    targetSub.casualLeave.monthlyCLLimit = finalMonthAllowed;
                    targetSub.casualLeave.pendingThisMonth = pendingCLDays;
                    targetSub.pendingAllDays = pendingAllDays;
                    targetSub.casualLeave.clBalance = Math.max(0, clBalance);
                    targetSub.compensatoryOff.cclBalance = Math.max(0, cclBalance);
                    targetSub.compensatoryOff.isIncluded = !!limitConfig.includeCCL;
                    targetSub.earnedLeave.elBalance = Math.max(0, elBalance);
                    targetSub.earnedLeave.isIncluded = !!limitConfig.includeEL;

                    // Absolute Cap (Inclusive Mode) or Additive
                    if (limitConfig.logicType === 'CAP_INCLUSIVE') {
                        const totalPotential = clBalance + (limitConfig.includeCCL ? cclBalance : 0) + (limitConfig.includeEL ? elBalance : 0);
                        targetSub.monthlyLimitPooled = finalMonthAllowed;
                        targetSub.monthlyAllowedLimit = Math.max(0, Math.min(totalPotential, finalMonthAllowed) - pendingAllDays);
                        targetSub.casualLeave.allowedRemaining = Math.max(0, Math.min(clBalance, finalMonthAllowed) - pendingCLDays);
                    } else {
                        targetSub.monthlyLimitPooled = finalMonthAllowed + (limitConfig.includeCCL ? cclBalance : 0) + (limitConfig.includeEL ? elBalance : 0);
                        targetSub.casualLeave.allowedRemaining = Math.max(0, Math.min(clBalance, finalMonthAllowed) - pendingCLDays);
                        targetSub.monthlyAllowedLimit = targetSub.casualLeave.allowedRemaining + 
                                                      (limitConfig.includeCCL ? cclBalance : 0) + 
                                                      (limitConfig.includeEL ? elBalance : 0);
                    }

                    // Persist monthly projection so reporting does not depend only on read-time calculations.
                    // This stores monthly cap + usage/pending locks and pooled allowed values.
                    await LeaveRegisterMonthlySnapshot.findOneAndUpdate(
                        {
                            employeeId: empId,
                            financialYear: fyName,
                            month: baseMonthNum,
                            year: baseYearNum
                        },
                        {
                            $set: {
                                empNo: entry.employee?.empNo || emp?.emp_no || '',
                                monthlyCLLimit: Number(finalMonthAllowed) || 0,
                                clUsedThisMonth: Number(targetSub.casualLeave?.usedThisMonth || 0),
                                clPendingThisMonth: Number(pendingCLDays || 0),
                                clLockedThisMonth: Number((targetSub.casualLeave?.usedThisMonth || 0) + (pendingCLDays || 0)),
                                clAllowedRemaining: Number(targetSub.casualLeave?.allowedRemaining || 0),
                                monthlyLimitPooled: Number(targetSub.monthlyLimitPooled || 0),
                                monthlyAllowedLimit: Number(targetSub.monthlyAllowedLimit || 0),
                                pendingAllDays: Number(pendingAllDays || 0),
                                clBalance: Number(clBalance || 0),
                                cclBalance: Number(cclBalance || 0),
                                elBalance: Number(elBalance || 0),
                                policySnapshot: {
                                    mode: mode || 'accumulative',
                                    defaultMonthlyCap: Number(defaultMonthlyCap ?? 1),
                                    maxUsableLimit: Number(maxUsableLimit ?? 4),
                                    protectFutureMonths: !!protectFutureMonths,
                                    includeCCL: !!limitConfig.includeCCL,
                                    includeEL: !!limitConfig.includeEL,
                                    logicType: limitConfig.logicType || 'ADDITIVE'
                                }
                            }
                        },
                        { upsert: true, new: false }
                    );
                }
            }


            return groupedData;
        } catch (error) {
            console.error('Error getting leave register:', error);
            throw error;
        }
    }

    /**
     * Get employee leave ledger
     */
    async getEmployeeLedger(employeeId, leaveType, startDate, endDate) {
        try {
            const ledger = await LeaveRegister.getEmployeeLedger(employeeId, leaveType, startDate, endDate);

            return {
                employeeId,
                leaveType,
                startDate,
                endDate,
                transactions: ledger,
                openingBalance: ledger.length > 0 ? ledger[0].openingBalance : 0,
                closingBalance: ledger.length > 0 ? ledger[ledger.length - 1].closingBalance : 0,
                totalCredits: ledger.filter(t => t.transactionType === 'CREDIT').reduce((sum, t) => sum + t.days, 0),
                totalDebits: ledger.filter(t => t.transactionType === 'DEBIT').reduce((sum, t) => sum + t.days, 0)
            };
        } catch (error) {
            console.error('Error getting employee ledger:', error);
            throw error;
        }
    }

    /**
     * Get employee's complete leave register
     */
    async getEmployeeRegister(employeeId, options = {}) {
        try {
            const { financialYear = null, fyStart = null } = options;
            const ledgerQuery = { employeeId };
            if (financialYear) ledgerQuery.financialYear = financialYear;

            // Get all leave transactions for this employee
            const allTransactions = await LeaveRegister.find(ledgerQuery)
                .sort({ year: 1, month: 1, createdAt: 1 })
                .lean();

            // For UI year drill-down we must build the 12-month sequence using payroll-cycle
            // month/year (because ledger month label is based on payroll cycle end month).
            let monthsInOrderOverride = null;
            if (fyStart) {
                const dateCycleService = require('./dateCycleService');
                monthsInOrderOverride = [];
                const base = new Date(fyStart);
                base.setDate(15);
                for (let i = 0; i < 12; i++) {
                    const repDate = new Date(base);
                    repDate.setMonth(base.getMonth() + i);
                    repDate.setDate(15);
                    const periodInfo = await dateCycleService.getPeriodInfo(repDate);
                    const m = periodInfo.payrollCycle.month;
                    const y = periodInfo.payrollCycle.year;
                    monthsInOrderOverride.push({ month: m, year: y, key: `${y}-${m}` });
                }
            }

            // Use the yearly grouping logic
            const grouped = this.groupByEmployeeYearly(allTransactions, fyStart, monthsInOrderOverride);

            let employeeLedger = grouped[0] || {
                employeeId,
                monthlySubLedgers: [],
                yearlySummary: {}
            };

            // If there are no transactions, still return a full 12-month sequence for UI stability.
            if ((!employeeLedger.monthlySubLedgers || employeeLedger.monthlySubLedgers.length === 0) && monthsInOrderOverride) {
                employeeLedger.monthlySubLedgers = monthsInOrderOverride.map(mi => ({
                    month: mi.month,
                    year: mi.year,
                    casualLeave: { openingBalance: 0, accruedThisMonth: 0, earnedCCL: 0, usedThisMonth: 0, expired: 0, balance: 0, carryForward: 0, adjustments: 0 },
                    earnedLeave: { openingBalance: 0, accruedThisMonth: 0, usedThisMonth: 0, balance: 0, adjustments: 0 },
                    compensatoryOff: { openingBalance: 0, earned: 0, used: 0, expired: 0, balance: 0, adjustments: 0 },
                    totalPaidBalance: 0,
                    transactions: []
                }));
            }

            // Enhance with yearly summary
            const yearlySummary = {
                CL: { totalCredits: 0, totalDebits: 0, adjustments: 0 },
                EL: { totalCredits: 0, totalDebits: 0, adjustments: 0 },
                CCL: { totalCredits: 0, totalDebits: 0, adjustments: 0 }
            };

            allTransactions.forEach(tx => {
                const type = tx.leaveType;
                if (yearlySummary[type]) {
                    if (tx.transactionType === 'CREDIT') yearlySummary[type].totalCredits += tx.days;
                    else if (tx.transactionType === 'DEBIT') yearlySummary[type].totalDebits += tx.days;
                    else if (tx.transactionType === 'ADJUSTMENT') yearlySummary[type].adjustments += tx.days;
                }
            });
            employeeLedger.yearlySummary = yearlySummary;

            // Fetch basic employee info to ensure all fields are present for the modal
            const employee = await Employee.findById(employeeId)
                .select('_id emp_no employee_name designation_id department_id division_id doj is_active')
                .populate('designation_id', 'name')
                .populate('department_id', 'name')
                .populate('division_id', 'name')
                .lean();

            if (employee) {
                employeeLedger.employeeName = employee.employee_name;
                employeeLedger.empNo = employee.emp_no;
                employeeLedger.designation = (employee.designation_id && employee.designation_id.name) || 'N/A';
                employeeLedger.department = (employee.department_id && employee.department_id.name) || 'N/A';
                employeeLedger.divisionName = (employee.division_id && employee.division_id.name) || 'N/A';
                employeeLedger.dateOfJoining = employee.doj;
                employeeLedger.employmentStatus = employee.is_active ? 'active' : 'inactive';
            }

            return employeeLedger;
        } catch (error) {
            console.error('Error getting employee register:', error);
            throw error;
        }
    }

    /**
     * Get current balance for employee
     */
    async getCurrentBalance(employeeId, leaveType, asOfDate = new Date()) {
        try {
            const balance = await LeaveRegister.getEmployeeBalance(employeeId, leaveType, asOfDate);
            return balance ? balance.closingBalance : 0;
        } catch (error) {
            console.error('Error getting current balance:', error);
            throw error;
        }
    }

    /**
     * Helper methods
     */
    calculateClosingBalance(openingBalance, transactionData) {
        const { transactionType, days } = transactionData;

        if (transactionType === 'CREDIT') {
            return openingBalance + days;
        } else if (transactionType === 'DEBIT' || transactionType === 'EXPIRY') {
            return Math.max(0, openingBalance - days);
        } else if (transactionType === 'ADJUSTMENT') {
            return days; // For adjustments, set directly
        }
        return openingBalance;
    }

    /**
     * Group transactions by employee with monthly summary breakdown
     */
    /**
     * Group transactions by employee with monthly sub-ledgers and individual transactions.
     */
    groupByEmployeeYearly(transactions, fyStart = null, monthsInOrderOverride = null) {
        const grouped = {};

        // 1. Group transactions by employee
        transactions.forEach(transaction => {
            const employeeId = transaction.employeeId._id || transaction.employeeId.id || transaction.employeeId;
            const empKey = employeeId.toString();
            const monthNum = transaction.month;
            const yearNum = transaction.year;
            const monthKey = `${yearNum}-${monthNum}`;

            if (!grouped[empKey]) {
                grouped[empKey] = {
                    employee: {
                        id: employeeId,
                        empNo: transaction.empNo,
                        name: transaction.employeeName,
                        designation: transaction.designation,
                        department: transaction.department,
                        division: transaction.divisionName,
                        doj: transaction.dateOfJoining,
                        status: transaction.employmentStatus
                    },
                    months: {}
                };
            }

            if (!grouped[empKey].months[monthKey]) {
                grouped[empKey].months[monthKey] = {
                    month: monthNum,
                    year: yearNum,
                    casualLeave: { openingBalance: 0, accruedThisMonth: 0, earnedCCL: 0, usedThisMonth: 0, expired: 0, balance: 0, carryForward: 0, adjustments: 0 },
                    earnedLeave: { openingBalance: 0, accruedThisMonth: 0, usedThisMonth: 0, balance: 0, adjustments: 0 },
                    compensatoryOff: { openingBalance: 0, earned: 0, used: 0, expired: 0, balance: 0, adjustments: 0 },
                    totalPaidBalance: 0,
                    transactions: []
                };
            }

            const monthData = grouped[empKey].months[monthKey];
            monthData.transactions.push(transaction);

            const leaveType = transaction.leaveType;
            const type = transaction.transactionType;
            const days = transaction.days;

            if (leaveType === 'CL') {
                const cl = monthData.casualLeave;
                cl.balance = transaction.closingBalance;
                if (type === 'CREDIT') {
                    if (transaction.autoGeneratedType === 'INITIAL_BALANCE') cl.accruedThisMonth += days;
                    else if (transaction.reason?.includes('CCL')) cl.earnedCCL += days;
                    else cl.accruedThisMonth += days;
                }
                else if (type === 'DEBIT') cl.usedThisMonth += days;
                else if (type === 'EXPIRY') cl.expired += days;
                else if (type === 'ADJUSTMENT') cl.adjustments += days;
            } else if (leaveType === 'EL') {
                const el = monthData.earnedLeave;
                el.balance = transaction.closingBalance;
                if (type === 'CREDIT') el.accruedThisMonth += days;
                else if (type === 'DEBIT') el.usedThisMonth += days;
                else if (type === 'ADJUSTMENT') el.adjustments += days;
            } else if (leaveType === 'CCL') {
                const ccl = monthData.compensatoryOff;
                ccl.balance = transaction.closingBalance;
                if (type === 'CREDIT') ccl.earned += days;
                else if (type === 'DEBIT') ccl.used += days;
                else if (type === 'EXPIRY') ccl.expired += days;
                else if (type === 'ADJUSTMENT') ccl.adjustments += days;
            }
        });

        // 2. Resolve full 12-month sequence for the financial year (or at least all months up to latest activity)
        return Object.values(grouped).map(empEntry => {
            // Determine full sequence of months to show if fyStart was provided
            let monthsInOrder = [];
            if (fyStart) {
                const monthsInOrderSource = Array.isArray(monthsInOrderOverride) && monthsInOrderOverride.length > 0
                    ? monthsInOrderOverride
                    : (() => {
                        const fyIst = extractISTComponents(fyStart);
                        const seq = [];
                        let m = fyIst.month;
                        let y = fyIst.year;
                        for (let i = 0; i < 12; i++) {
                            seq.push({ month: m, year: y, key: `${y}-${m}` });
                            if (m === 12) {
                                m = 1;
                                y += 1;
                            } else {
                                m += 1;
                            }
                        }
                        return seq;
                    })();

                for (const mi of monthsInOrderSource) {
                    const { month: m, year: y, key } = mi;
                    
                    if (empEntry.months[key]) {
                        monthsInOrder.push(empEntry.months[key]);
                    } else {
                        // Create placeholder month
                        monthsInOrder.push({
                            month: m,
                            year: y,
                            casualLeave: { openingBalance: 0, accruedThisMonth: 0, earnedCCL: 0, usedThisMonth: 0, expired: 0, balance: 0, carryForward: 0 },
                            earnedLeave: { openingBalance: 0, accruedThisMonth: 0, usedThisMonth: 0, balance: 0 },
                            compensatoryOff: { openingBalance: 0, earned: 0, used: 0, expired: 0, balance: 0 },
                            totalPaidBalance: 0,
                            transactions: []
                        });
                    }
                }
            } else {
                monthsInOrder = Object.values(empEntry.months).sort((a, b) => (a.year - b.year) || (a.month - b.month));
            }
            
            // 3. Chain balances across the sequence
            if (monthsInOrder.length > 0) {
                for (let i = 0; i < monthsInOrder.length; i++) {
                    const m = monthsInOrder[i];
                    
                    if (i > 0) {
                        const prevM = monthsInOrder[i - 1];
                        m.casualLeave.openingBalance = prevM.casualLeave.closingBalance ?? prevM.casualLeave.balance;
                        m.earnedLeave.openingBalance = prevM.earnedLeave.closingBalance ?? prevM.earnedLeave.balance;
                        m.compensatoryOff.openingBalance = prevM.compensatoryOff.closingBalance ?? prevM.compensatoryOff.balance;
                    } else {
                        if (m.transactions.length > 0) {
                            m.casualLeave.openingBalance = m.transactions.find(tx => tx.leaveType === 'CL')?.openingBalance || 0;
                            m.earnedLeave.openingBalance = m.transactions.find(tx => tx.leaveType === 'EL')?.openingBalance || 0;
                            m.compensatoryOff.openingBalance = m.transactions.find(tx => tx.leaveType === 'CCL')?.openingBalance || 0;
                        }
                    }

                    if (m.transactions.length === 0) {
                        m.casualLeave.balance = m.casualLeave.openingBalance;
                        m.earnedLeave.balance = m.earnedLeave.openingBalance;
                        m.compensatoryOff.balance = m.compensatoryOff.openingBalance;
                    } else {
                        const deltaCL = m.casualLeave.accruedThisMonth + m.casualLeave.earnedCCL - m.casualLeave.usedThisMonth - m.casualLeave.expired + m.casualLeave.adjustments;
                        const deltaEL = m.earnedLeave.accruedThisMonth - m.earnedLeave.usedThisMonth + m.earnedLeave.adjustments;
                        const deltaCCL = m.compensatoryOff.earned - m.compensatoryOff.used - m.compensatoryOff.expired + m.compensatoryOff.adjustments;
                        
                        m.casualLeave.balance = m.casualLeave.openingBalance + deltaCL;
                        m.earnedLeave.balance = m.earnedLeave.openingBalance + deltaEL;
                        m.compensatoryOff.balance = m.compensatoryOff.openingBalance + deltaCCL;
                    }

                    m.casualLeave.closingBalance = m.casualLeave.balance;
                    m.earnedLeave.closingBalance = m.earnedLeave.balance;
                    m.compensatoryOff.closingBalance = m.compensatoryOff.balance;
                    m.totalPaidBalance = m.casualLeave.balance + m.earnedLeave.balance + m.compensatoryOff.balance;
                }
            }


            // 4. Calculate Yearly Summary from the sub-ledgers

            const yearlySummary = {
                CL: { openingBalance: 0, totalCredits: 0, totalDebits: 0, adjustments: 0, closingBalance: 0 },
                EL: { openingBalance: 0, totalCredits: 0, totalDebits: 0, adjustments: 0, closingBalance: 0 },
                CCL: { openingBalance: 0, totalCredits: 0, totalDebits: 0, adjustments: 0, closingBalance: 0 }
            };

            if (monthsInOrder.length > 0) {
                // Initial opening balances from the first month in the financial year
                yearlySummary.CL.openingBalance = monthsInOrder[0].casualLeave.openingBalance;
                yearlySummary.EL.openingBalance = monthsInOrder[0].earnedLeave.openingBalance;
                yearlySummary.CCL.openingBalance = monthsInOrder[0].compensatoryOff.openingBalance;

                // Final closing balances from the last month in the financial year
                yearlySummary.CL.closingBalance = monthsInOrder[monthsInOrder.length - 1].casualLeave.closingBalance;
                yearlySummary.EL.closingBalance = monthsInOrder[monthsInOrder.length - 1].earnedLeave.closingBalance;
                yearlySummary.CCL.closingBalance = monthsInOrder[monthsInOrder.length - 1].compensatoryOff.closingBalance;

                // Aggregate credits/debits across all 12 months
                monthsInOrder.forEach(m => {
                    yearlySummary.CL.totalCredits += m.casualLeave.accruedThisMonth + m.casualLeave.earnedCCL;
                    yearlySummary.CL.totalDebits += m.casualLeave.usedThisMonth;
                    
                    yearlySummary.EL.totalCredits += m.earnedLeave.accruedThisMonth;
                    yearlySummary.EL.totalDebits += m.earnedLeave.usedThisMonth;
                    
                    yearlySummary.CCL.totalCredits += m.compensatoryOff.earned;
                    yearlySummary.CCL.totalDebits += m.compensatoryOff.used;

                    // Sum adjustments from transactions
                    m.transactions.forEach(tx => {
                        if (tx.transactionType === 'ADJUSTMENT') {
                            if (tx.leaveType === 'CL') yearlySummary.CL.adjustments += tx.days;
                            else if (tx.leaveType === 'EL') yearlySummary.EL.adjustments += tx.days;
                            else if (tx.leaveType === 'CCL') yearlySummary.CCL.adjustments += tx.days;
                        }
                    });
                });
            }

            empEntry.yearlySummary = yearlySummary;
            empEntry.monthlySubLedgers = monthsInOrder;
            delete empEntry.months;
            return empEntry;
        });


    }

    async updateEmployeeBalance(employeeId, leaveType) {
        try {
            // Get the absolute latest balance regardless of date for the employee model sync
            const currentBalance = await this.getCurrentBalance(employeeId, leaveType, new Date('9999-12-31'));

            const updateField = this.getEmployeeBalanceField(leaveType);
            console.log(`[LeaveRegister] Syncing ${leaveType} balance (${currentBalance}) to Employee field ${updateField}`);
            await Employee.findByIdAndUpdate(employeeId, {
                [updateField]: currentBalance
            });
        } catch (error) {
            console.error('Error updating employee balance:', error);
            // Don't throw error here as it's not critical
        }
    }

    getEmployeeBalanceField(leaveType) {
        // EL (Earned Leave) is stored in Employee.paidLeaves for legacy naming
        const fieldMap = {
            'EL': 'paidLeaves',
            'CL': 'casualLeaves',
            'SL': 'sickLeaves',
            'ML': 'maternityLeaves',
            'OD': 'onDutyLeaves',
            'CCL': 'compensatoryOffs'
        };
        return fieldMap[leaveType] || 'paidLeaves';
    }
}

module.exports = new LeaveRegisterService();
