/**
 * Persists monthly pool ceiling & pooled consumption on LeaveRegisterYear.months[] (register UI).
 * Ceiling = scheduled CL+CCL[+EL when includeEL]; consumption = policy-weighted cap days (pending + approved).
 * Per-type apply limits are enforced separately (maxDaysByType).
 */

const LeaveRegisterYear = require('../model/LeaveRegisterYear');
const Leave = require('../model/Leave');
const LeavePolicySettings = require('../../settings/model/LeavePolicySettings');
const dateCycleService = require('./dateCycleService');
const {
  CAP_COUNT_STATUSES,
  computeScheduledPoolApplyCeiling,
  sumCountedCapDaysForLeaveInPeriod,
  sumLeaveTypeDaysForLeaveInPeriod,
  getConfiguredMonthlyTypeCap,
  isPerTypeMonthlyCapActive,
} = require('./monthlyApplicationCapService');

function findSlotIndex(months, pcMonth, pcYear) {
  if (!Array.isArray(months)) return -1;
  return months.findIndex(
    (m) =>
      Number(m.payrollCycleMonth) === Number(pcMonth) &&
      Number(m.payrollCycleYear) === Number(pcYear)
  );
}

/**
 * Recompute and save monthlyApply* fields on the payroll slot that contains fromDate.
 */
async function syncStoredMonthApplyFieldsForEmployeeDate(employeeId, fromDate) {
  if (!employeeId || !fromDate) return { ok: false, reason: 'bad_args' };
  const policy = await LeavePolicySettings.getSettings().catch(() => ({}));
  const periodInfo = await dateCycleService.getPeriodInfo(fromDate);
  const { startDate: start, endDate: end } = periodInfo.payrollCycle;
  const pc = periodInfo.payrollCycle;
  const fy = await dateCycleService.getFinancialYearForDate(fromDate);

  const doc = await LeaveRegisterYear.findOne({
    employeeId,
    financialYear: fy.name,
  });
  if (!doc || !doc.months?.length) return { ok: false, reason: 'no_year_doc' };

  const idx = findSlotIndex(doc.months, pc.month, pc.year);
  if (idx < 0) return { ok: false, reason: 'no_slot' };

  const slot = doc.months[idx];
  const scheduled = {
    clCredits: slot.clCredits,
    compensatoryOffs: slot.compensatoryOffs,
    elCredits: slot.elCredits,
  };
  const ceilingRaw = computeScheduledPoolApplyCeiling(scheduled, policy);
  if (ceilingRaw != null && Number.isFinite(ceilingRaw)) {
    slot.monthlyApplyCeiling = Math.max(0, ceilingRaw);
  }

  const leaves = await Leave.find({
    employeeId,
    isActive: true,
    status: { $in: CAP_COUNT_STATUSES },
    fromDate: { $lte: end },
    toDate: { $gte: start },
  })
    .select('leaveType numberOfDays status splitStatus fromDate toDate')
    .lean();

  let consumed = 0;
  let locked = 0;
  let approvedSum = 0;
  for (const l of leaves) {
    const d = await sumCountedCapDaysForLeaveInPeriod(l, policy, start, end);
    if (d <= 0) continue;
    consumed += d;
    if (String(l.status) === 'approved') approvedSum += d;
    else locked += d;
  }

  // Include admin/manual "Used" overrides that we store as DEBIT transactions
  // (so UI "Left" updates even when there are no Leave rows for the month).
  const includeEL =
    !!policy?.earnedLeave?.enabled &&
    !!policy?.monthlyLeaveApplicationCap?.includeEL &&
    policy?.earnedLeave?.useAsPaidInPayroll === false;
  const manualUsedTxs = Array.isArray(slot?.transactions) ? slot.transactions : [];
  let manualUsedTotal = 0;
  for (const tx of manualUsedTxs) {
    const txType = String(tx?.transactionType || '').toUpperCase();
    if (txType !== 'DEBIT') continue;
    const autoType = String(tx?.autoGeneratedType || '');
    if (!autoType.startsWith('MANUAL_SLOT_USED_')) continue;
    const lt = String(tx?.leaveType || '').toUpperCase();
    if (lt === 'EL' && !includeEL) continue;
    manualUsedTotal += Math.max(0, Number(tx?.days) || 0);
  }

  consumed += manualUsedTotal;
  approvedSum += manualUsedTotal; // treat admin used as approved consumption (not pending lock)

  slot.monthlyApplyConsumed = consumed;
  slot.monthlyApplyLocked = locked;
  slot.monthlyApplyApproved = approvedSum;
  slot.monthlyApplySyncedAt = new Date();

  doc.markModified(`months.${idx}`);
  await doc.save();
  return {
    ok: true,
    ceiling: slot.monthlyApplyCeiling,
    consumed,
    locked,
    approvedSum,
  };
}

/**
 * Context for leave apply UI (CL): stored slot caps + FY balances.
 * @param {boolean} [options.refresh] - force sync before read
 */
async function getApplyPeriodContextForEmployee(employeeId, fromDate, options = {}) {
  const { refresh = false, leaveType = 'CL' } = options;
  const requestedType = String(leaveType || 'CL').toUpperCase();
  if (!employeeId || !fromDate) {
    return { ok: false, error: 'employeeId and fromDate required' };
  }

  if (refresh) {
    await syncStoredMonthApplyFieldsForEmployeeDate(employeeId, fromDate);
  }

  const policy = await LeavePolicySettings.getSettings().catch(() => ({}));
  const periodInfo = await dateCycleService.getPeriodInfo(fromDate);
  const start = periodInfo.payrollCycle.startDate;
  const end = periodInfo.payrollCycle.endDate;
  const pc = periodInfo.payrollCycle;
  const fy = await dateCycleService.getFinancialYearForDate(fromDate);

  let doc = await LeaveRegisterYear.findOne({
    employeeId,
    financialYear: fy.name,
  }).lean();

  if (!doc?.months?.length) {
    return {
      ok: true,
      hasYearDoc: false,
      financialYear: fy.name,
      payrollCycle: { start, end, month: pc.month, year: pc.year },
    };
  }

  const idx = findSlotIndex(doc.months, pc.month, pc.year);
  if (idx < 0) {
    return {
      ok: true,
      hasYearDoc: true,
      hasSlot: false,
      financialYear: fy.name,
      payrollCycle: { start, end, month: pc.month, year: pc.year },
      balances: {
        cl: doc.casualBalance,
        ccl: doc.compensatoryOffBalance,
        el: doc.earnedLeaveBalance,
      },
    };
  }

  const slot = doc.months[idx];
  let needsSync =
    refresh ||
    slot.monthlyApplyCeiling == null ||
    slot.monthlyApplyConsumed == null;

  if (needsSync) {
    await syncStoredMonthApplyFieldsForEmployeeDate(employeeId, fromDate);
    doc = await LeaveRegisterYear.findOne({
      employeeId,
      financialYear: fy.name,
    }).lean();
  }

  const slotFresh = doc.months[idx];
  const ceiling = slotFresh.monthlyApplyCeiling;
  const consumed = slotFresh.monthlyApplyConsumed;
  const locked = slotFresh.monthlyApplyLocked;
  const approvedSum = slotFresh.monthlyApplyApproved;

  const remaining =
    ceiling != null && consumed != null
      ? Math.max(0, Number(ceiling) - Number(consumed))
      : null;

  const includeEL =
    !!policy?.earnedLeave?.enabled &&
    !!policy?.monthlyLeaveApplicationCap?.includeEL &&
    policy?.earnedLeave?.useAsPaidInPayroll === false;

  const typeScheduledMap = {
    CL: Number(slotFresh.clCredits) || 0,
    CCL: Number(slotFresh.compensatoryOffs) || 0,
    EL: includeEL ? Number(slotFresh.elCredits) || 0 : 0,
  };
  const typeBalanceMap = {
    CL: Number(doc.casualBalance) || 0,
    CCL: Number(doc.compensatoryOffBalance) || 0,
    EL: includeEL ? Number(doc.earnedLeaveBalance) || 0 : 0,
  };
  const leaves = await Leave.find({
    employeeId,
    isActive: true,
    status: { $in: CAP_COUNT_STATUSES },
    fromDate: { $lte: end },
    toDate: { $gte: start },
  })
    .select('_id leaveType numberOfDays status splitStatus fromDate toDate')
    .lean();
  let typeApproved = 0;
  let typeLocked = 0;
  for (const row of leaves) {
    const d = await sumLeaveTypeDaysForLeaveInPeriod(row, requestedType, start, end);
    if (d <= 0) continue;
    if (String(row.status) === 'approved' && String(row.splitStatus || '') !== 'pending_split') typeApproved += d;
    else typeLocked += d;
  }
  const typeConsumed = typeApproved + typeLocked;
  const typeCap = getConfiguredMonthlyTypeCap(policy, requestedType);
  const perTypeOn = isPerTypeMonthlyCapActive(policy, requestedType);
  const typeCapEnabled = perTypeOn;
  const typeCapValue = Number.isFinite(typeCap) && Number(typeCap) >= 0 ? Number(typeCap) : 0;
  const typeRemaining = perTypeOn ? Math.max(0, typeCapValue - typeConsumed) : null;

  return {
    ok: true,
    hasYearDoc: true,
    hasSlot: true,
    financialYear: fy.name,
    payrollLabel: slotFresh.label,
    payrollCycle: { start, end, month: pc.month, year: pc.year },
    scheduledCl: Number(slotFresh.clCredits) || 0,
    scheduledCcl: Number(slotFresh.compensatoryOffs) || 0,
    scheduledEl: includeEL ? Number(slotFresh.elCredits) || 0 : null,
    monthlyApplyCeiling: ceiling,
    monthlyApplyConsumed: consumed,
    monthlyApplyLocked: locked,
    monthlyApplyApproved: approvedSum,
    monthlyApplyRemaining: remaining,
    monthlyApplySyncedAt: slotFresh.monthlyApplySyncedAt || null,
    balances: {
      cl: doc.casualBalance,
      ccl: doc.compensatoryOffBalance,
      el: includeEL ? doc.earnedLeaveBalance : null,
    },
    includeELInMonthlyPool: includeEL,
    leaveType: requestedType,
    selectedType: {
      leaveType: requestedType,
      scheduled: typeScheduledMap[requestedType] ?? 0,
      balance: typeBalanceMap[requestedType] ?? 0,
      cap: typeCapValue,
      capEnabled: typeCapEnabled,
      approved: typeApproved,
      locked: typeLocked,
      consumed: typeConsumed,
      remaining: typeRemaining,
    },
  };
}

function scheduleSyncMonthApply(employeeId, fromDate) {
  if (!employeeId || !fromDate) return;
  setImmediate(() => {
    syncStoredMonthApplyFieldsForEmployeeDate(employeeId, fromDate).catch((e) => {
      console.warn('[monthlyApply sync]', e?.message || e);
    });
  });
}

module.exports = {
  syncStoredMonthApplyFieldsForEmployeeDate,
  getApplyPeriodContextForEmployee,
  scheduleSyncMonthApply,
};
